### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Hopson97** [jeanqasaur/women-in-programming-languages-research#25]
What's the purpose of this repository? :D

**Comment by LeifAndersen** [comment]
This is actually discussed on [this mailing list thread][1]. You will have to sign up to the list to read it (iirc, the default is to send you no mail), which you can do [here][2].

[1]: https://groups.google.com/forum/#!topic/intersectional-types/Wixv5Ue3aF0
[2]: https://www.cs.cmu.edu/~cmartens/intersection.html

**Comment by Hopson97** [comment]
Thanks!
